title: Andrew Delis 
description: > 
  
  <br><br>
  <a href="https://www.linkedin.com/in/andrewdelis/">LinkedIn Profile</a>  

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme