title: Andrew Delis
logo: "/images/IMG_7282 (1) (2) (1).png?raw=true" 
description: > 
  I'm Abhiram Mannam, a data scientist and analyst. My formal education as a computer engineer included programming and machine learning, so as a result, I am more focused on analytical thinking and learning new things. I am pursuing an MS in Business Analytics at David Eccles School of Business, University of Utah.
  <br><br>
  <a href="https://www.linkedin.com/in/abhiram-mannam/">View My LinkedIn Profile</a>  

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

