title: Andrew Delis

logo: "/images/li_pic.jpeg?raw=true"

description: > 
  My name is Andrew Delis. I have a diverse work history that has required me learn how to adapt to different industry customs. My experience has taught me that there are many ways to be additive and useful. I am personally passionate about quality, storytelling, and data.
  <br><br>
  <a href="https://www.linkedin.com/in/andrewdelis/">View My LinkedIn Profile </a>

remote_theme: pages-themes/minimal@v0.2.0

plugins:
  - jekyll-remote-theme