title: Your Portfolio
description: Data Analytics Projects Portfolio
author: Your Name

# GitHub Pages settings
plugins:
  - jekyll-relative-links

# Exclude files from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

# Enable relative links
relative_links:
  enabled: true
  collections: true