title: Andrew Delis
logo: "/images/li_pic.jpeg?raw=true" 
description: > 
  My name is Andrew Delis.
  <br><br>
  <a href="https://www.linkedin.com/in/andrewdelis/">View My LinkedIn Profile</a>  

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

